//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcmsBankIsraelProxy.SoapClients.SapPicture
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://boi.org.il/HR_Comda_pic", ConfigurationName="CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi")]
    public interface comda_pic_mi
    {
        
        // CODEGEN: Generating message contract since the operation poli_pic_mi is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse poli_pic_mi(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse> poli_pic_miAsync(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boi.org.il/HR_Polimil_Pic")]
    public partial class poli_pic_req_dt
    {
        
        private string iDNumField;
        
        private string cardNumField;
        
        private string pictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDNum
        {
            get
            {
                return this.iDNumField;
            }
            set
            {
                this.iDNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CardNum
        {
            get
            {
                return this.cardNumField;
            }
            set
            {
                this.cardNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Picture
        {
            get
            {
                return this.pictureField;
            }
            set
            {
                this.pictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://boi.org.il/HR_Polimil_Pic")]
    public partial class poli_pic_res_dtReturnMessage
    {
        
        private string typeField;
        
        private string messageField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class poli_pic_miRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://boi.org.il/HR_Polimil_Pic", Order=0)]
        public CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_req_dt comda_pic_req_mt;
        
        public poli_pic_miRequest()
        {
        }
        
        public poli_pic_miRequest(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_req_dt comda_pic_req_mt)
        {
            this.comda_pic_req_mt = comda_pic_req_mt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class poli_pic_miResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://boi.org.il/HR_Polimil_Pic", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ReturnMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_res_dtReturnMessage[] poli_pic_res_mt;
        
        public poli_pic_miResponse()
        {
        }
        
        public poli_pic_miResponse(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_res_dtReturnMessage[] poli_pic_res_mt)
        {
            this.poli_pic_res_mt = poli_pic_res_mt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface comda_pic_miChannel : CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class comda_pic_miClient : System.ServiceModel.ClientBase<CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi>, CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comda_pic_miClient(EndpointConfiguration endpointConfiguration) : 
                base(comda_pic_miClient.GetBindingForEndpoint(endpointConfiguration), comda_pic_miClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comda_pic_miClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comda_pic_miClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comda_pic_miClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comda_pic_miClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comda_pic_miClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi.poli_pic_mi(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest request)
        {
            return base.Channel.poli_pic_mi(request);
        }
        
        public CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_res_dtReturnMessage[] poli_pic_mi(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_req_dt comda_pic_req_mt)
        {
            CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest inValue = new CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest();
            inValue.comda_pic_req_mt = comda_pic_req_mt;
            CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse retVal = ((CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi)(this)).poli_pic_mi(inValue);
            return retVal.poli_pic_res_mt;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse> CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi.poli_pic_miAsync(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest request)
        {
            return base.Channel.poli_pic_miAsync(request);
        }
        
        public System.Threading.Tasks.Task<CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miResponse> poli_pic_miAsync(CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_req_dt comda_pic_req_mt)
        {
            CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest inValue = new CcmsBankIsraelProxy.SoapClients.SapPicture.poli_pic_miRequest();
            inValue.comda_pic_req_mt = comda_pic_req_mt;
            return ((CcmsBankIsraelProxy.SoapClients.SapPicture.comda_pic_mi)(this)).poli_pic_miAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://sapwaexq.ad.boi.gov.il:50000/XISOAPAdapter/MessageServlet?senderParty=&sen" +
                        "derService=BankIsrael_QA&receiverParty=&receiverService=&interface=comda_pic_mi&" +
                        "interfaceNamespace=http%3A%2F%2Fboi.org.il%2FHR_Comda_pic");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://sapwaexq.ad.boi.gov.il:50001/XISOAPAdapter/MessageServlet?senderParty=&se" +
                        "nderService=BankIsrael_QA&receiverParty=&receiverService=&interface=comda_pic_mi" +
                        "&interfaceNamespace=http%3A%2F%2Fboi.org.il%2FHR_Comda_pic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
