@CcmsBankIsraelProxy_HostAddress = http://localhost:5000

### Health Check
GET {{CcmsBankIsraelProxy_HostAddress}}/Boi
Accept: application/json

### Get Employee by ID
GET {{CcmsBankIsraelProxy_HostAddress}}/Boi/employee/123456789
Accept: application/json

### Process CCMS Callback (Create/Update)
POST {{CcmsBankIsraelProxy_HostAddress}}/Boi/process
Content-Type: application/json

{
  "Id": 1,
  "Operation": 1,
  "EntityTypeId": 1,
  "EntityId": 100,
  "Issuer": "CCMS",
  "CardData": "{\"ID_Number\":\"123456789\",\"Employee_Number\":\"EMP001\",\"CardNo\":\"CARD001\",\"FirstName_Hb\":\"ישראל\",\"LastName_Hb\":\"ישראלי\",\"Phone\":\"0501234567\"}"
}

### Update Picture
POST {{CcmsBankIsraelProxy_HostAddress}}/Boi/picture
Content-Type: application/json

{
  "idNum": "123456789",
  "cardNum": "CARD001",
  "picture": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
}

### Send SMS
POST {{CcmsBankIsraelProxy_HostAddress}}/Boi/sms
Content-Type: application/json

{
  "toNumbers": "0501234567",
  "message": "Test SMS from BOI Proxy"
}
